### ISSUE TITLE
КОЛ-ВО ЭНЕРГОСОВ

### ISSUE THREAD

**Issue by qqq4u** [not-Whale/vk_bot#3]
каждому добавить инфу о количестве энергосов у него в комнате. Рассмотреть всевозможные ситуации в общем, я думаю ты выкупишь. Количество будем менять в ручную, так быстрее

**Comment by not-Whale** [comment]
Я бы добавил сюда просто контекстные команды для работы с ботом для администраторов, как и с входом/выходом
